# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'minna-no-hologram-apis'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health]
    port = 8080
    type = "http"
    interval = "30s"
    timeout = "10s"
    grace_period = "120s"
    method = "GET"
    path = "/actuator/health"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
