spring:
  application:
    name: minna-no-hologram-recommend
  output:
    ansi:
      enabled: detect # Auto-detect console capabilities
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: true
  web:
    resources:
      add-mappings: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

# SLM configuration
recommendation:
  model:
    # Model configuration
    # Use a model like "sentence-transformers/all-MiniLM-L6-v2"
    name: "sentence-transformers/all-MiniLM-L6-v2"
    path: models
    cache-dir: ${user.home}/.hologram-recommend/models
    embedding-dimension: 384 # 384 for MiniLM-L6-v2 (768 for larger models)
    max-length: 128
    batch-size: 16
    enabled: true
    # Options: huggingface, openai, tensorflow, mock
    provider: "huggingface"
    # API key for cloud-based models (leave empty for local models)
    api-key: ""
  # How many recommendations to return
  default-limit: 10
  min-similarity-score: 0.5
  # Precompute embeddings on startup and after adding new content
  precompute-embeddings: true
  # Cache configuration
  cache:
    enabled: true
    ttl-minutes: 30
    max-size: 1000

# OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method

# Logging configuration
logging:
  level:
    root: INFO
    com.betonamura: DEBUG
    org.springframework: INFO
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
