server:
  port: 8081
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: minna-no-hologram-recommend
  # TODO: Add actual database configuration when DB integration is needed
  # For now, using in-memory data structures
  output:
    ansi:
      enabled: detect
  mvc:
    throw-exception-if-no-handler-found: true

# SLM configuration
recommendation:
  model:
    name: "distilbert-base-uncased"
    path: models
    cache-dir: ${user.home}/.hologram-recommend/models
    embedding-dimension: 768
    max-length: 128
    batch-size: 16
  # How many recommendations to return
  default-limit: 10
  min-similarity-score: 0.5
  # Cache configuration
  cache:
    ttl-minutes: 30
    max-size: 1000

# OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method

# Logging configuration
logging:
  level:
    root: INFO
    com.betonamura: DEBUG
    org.springframework: INFO
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
