spring:
  application:
    name: minna-no-hologram-bff
  output:
    ansi:
      enabled: detect # Auto-detect console capabilities
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: true
  web:
    resources:
      add-mappings: false

server:
  port: 8080
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.betonamura.hologram: INFO
  file:
    name: logs/application.log
  pattern:
    console: "%clr(%d{HH:mm:ss}){blue} %clr(%-5p) %clr([%logger{0}]){cyan} %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name}] [%thread] %-5level %logger{36} - %msg%n"
